version: "3.9"

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672" # RabbitMQ default port for AMQP
      - "15672:15672" # RabbitMQ Management Console
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - ku-wongnai_ku-wongnai

  mysql:
    image: "mysql"
    ports:
      - "${FORWARD_DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    volumes:
      - "db_data:/var/lib/mysql"
      - "./docker/provision/mysql/init:/docker-entrypoint-initdb.d"
    networks:
      - mysql_network
      - ku-wongnai_ku-wongnai
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - "-ppassword"
      retries: 3
      timeout: 5s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8080:80
    depends_on:
      - mysql
    networks:
      - mysql_network

networks:
  mysql_network:
    driver: bridge
  ku-wongnai_ku-wongnai:
    external: true

volumes:
  db_data:
